# Generated by Django 4.2.7 on 2023-12-01 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("touragents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rating", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tour_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="touragents.touragent",
                    ),
                ),
            ],
        ),
    ]
